service: serverless-raffle

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

functions:
  register:
    handler: handler.register
    events:
      - http:
          path: enter
          method: post
  list:
    handler: handler.list
    events:
      - http:
          path: participants
          method: get

resources:
  Resources:
    serverlessRaffle:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: serverlessRaffle
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: date
            AttributeType: N
        KeySchema:
          - AttributeName: email
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
